spring:
  application:
    name: authserver
  datasource:
    url: jdbc:postgresql://localhost:5432/authDb
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 25
      minimum-idle: 12
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
